name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - ActionsScript
   
jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['generic/platform=iOS']
        xcode: ['/Applications/Xcode_12.4.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Dependencies
        run: |
          carthage bootstrap --no-use-binaries --platform iOS --cache-builds
          bundle exec pod install
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Build and test
        run: bundle exec fastlane scan --destination "${destination}" --scheme "TestProjectStage"
        env:
          destination: ${{ matrix.destination }}
          DEVELOPER_DIR: ${{ matrix.xcode }}
      

