name: CI

on:
  push:
    branches: [ ActionScriptShellscript ]
  pull_request:
    branches: [ master ]

jobs:
  build-sample:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    
    - name: Select xcodebuild
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Testing iOS app
      run:  chmod +x ./.github/scripts/test_app.sh
     
    - name: Build Sample
      run: xcodebuild clean build -allowProvisioningUpdates -workspace TestProject.xcworkspace -scheme TestProject -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="Apple Development" CODE_SIGNING_REQUIRED=YES ONLY_ACTIVE_ARCH=NO
    


