name: CI

on:
  push:
    branches: [ ProdNStageSwitchUsingConfig  ]
  pull_request:
    branches: [ master ]

jobs:
  build-sample:

    runs-on: macos-latest
    
    env:
        XC_VERSION: ${{ '12.4' }}
        XC_WORKSPACE: ${{ 'TestProject.xcworkspace' }}
        XC_SCHEME: ${{ 'TestProject' }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Select xcodebuild
      run: sudo xcode-select -switch /Applications/Xcode_$XC_VERSION.app
    
    - name: Build Sample
      run: xcodebuild clean build -allowProvisioningUpdates -workspace $XC_WORKSPACE -scheme $XC_SCHEME -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="YogiFi_App_GithubAction_Development" CODE_SIGNING_REQUIRED=YES ONLY_ACTIVE_ARCH=NO
    

