name: CI

on:
  push:
    branches: [ ActionScript ]
  pull_request:
    branches: [ master ]

jobs:
  build-sample:

    runs-on: macos-latest

        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Select xcodebuild
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    #- name: Testing Swift package
      #run:  chmod +x ./.github/scripts/test_swift_package.sh
      
    #- name: Testing Swift package
      #run: exec ./.github/scripts/test_swift_package.sh
      
    - name: Testing iOS app
      run: chmod +x ./.github/scripts/test_app.sh
         
    - name: Exceute iOS app
      run: exec ./.github/scripts/test_app.sh
      
    - name: Build Sample
      run: xcodebuild clean build -allowprov -workspace $XC_WORKSPACE -scheme $XC_SCHEME -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="Apple Development" CODE_SIGNING_REQUIRED=YES ONLY_ACTIVE_ARCH=NO
    










