name: CI

on:
  push:
    branches: [ ActionScript ]
  pull_request:
    branches: [ master ]

jobs:
  build-sample:

    runs-on: macos-latest
    env:
    
      CERTS_ENCRYPTION_PWD: ${{ secrets.CERTS_ENCRYPTION_PWD }}
      PROVISION_ENCRYPTION_PWD: ${{ secrets.PROVISION_ENCRYPTION_PWD }}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Select xcodebuild
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
   
#    - name: Install gpg
#      run: brew install gnupg
     
    - name: Setup provisioning profile
      run:  chmod +x ./.github/scripts/decrypt_secrets.sh
      
    - name: excute provisioning profile
      run:  exec ./.github/scripts/decrypt_secrets.sh
      
    - name: Testing iOS apps
      run: chmod +x ./.github/scripts/test_app.sh
         
    - name: Exceute iOS app
      run: exec ./.github/scripts/test_app.sh
    
      
#    - name: Testing Swift package
#      run:  chmod +x ./.github/scripts/test_swift_package.sh
      
#    - name: Testing Swift package
#      run: exec ./.github/scripts/test_swift_package.sh
    
    - name: Build Sample
      run: xcodebuild clean build -allowprov -workspace TestProject.xcworkspace -scheme TestProjectStage -destination generic/platform=iOS' CODE_SIGN_IDENTITY="Apple Development" CODE_SIGNING_REQUIRED=YES ONLY_ACTIVE_ARCH=NO











